apiVersion: v1
kind: Secret
metadata:
  name: db-secret
type: Opaque
data:
  POSTGRES_USERNAME: cG9zdGdyZXM= # Base64 for "postgres"
  POSTGRES_PASSWORD: dDMhS1FscFExZ1AxSGM= # Base64 for "t3!KQlpQ1gP1Hc"
