apiVersion: v1
kind: ConfigMap
metadata:
  name: verify-config
  namespace: microservices
data:
  application.properties: |
    spring.application.name=Login
    server.port=8446
    spring.datasource.driver-class-name=org.postgresql.Driver
    spring.datasource.username=${PGSQL_USER}
    spring.datasource.password=${PGSQL_PASSWORD}
    spring.datasource.url=jdbc:postgresql://db-verify-service:5432/cloud
    spring.jpa.hibernate.ddl-auto=update
    spring.jpa.show-sql=false
    server.servlet.session.timeout=30m
    jwt.secret=${JWT_SECRET}
    jwt.expiration=604800
    spring.data.redis.host=redis-service
    spring.data.redis.port=6379
    spring.data.redis.database=0