apiVersion: apps/v1
kind: Deployment
metadata:
  name: verify-deployment
  
spec:
  replicas: 3
  selector:
    matchLabels:
      app: verify
  template:
    metadata:
      labels:
        app: verify
    spec:
      containers:
      - name: verify
        image: tonyxie2017/unity-verify:latest
        ports:
        - containerPort: 8446
        volumeMounts:
        - name: config-volume
          mountPath: /config
        env:
        - name: SPRING_CONFIG_LOCATION
          value: "/config/application.properties"
        - name: POSTGRES_USER
          valueFrom:
            secretKeyRef:
              name: pgsql-secret
              key: username
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: pgsql-secret
              key: password
        - name: JWT_SECRET
          valueFrom:
            secretKeyRef:
              name: jwt-secret
              key: jwt-key
        resources:
          limits:
            cpu: "1"
            memory: "512Mi"
          requests:
            cpu: "0.5"
            memory: "256Mi"
      volumes:
      - name: config-volume
        configMap:
          name: verify-config
          items:
              - key: application.properties
                path: application.properties
---
apiVersion: v1
kind: Service
metadata:
  name: verify-service
  
spec:
  selector:
    app: verify
  ports:
    - protocol: TCP
      port: 8446
      targetPort: 8446