apiVersion: apps/v1
kind: Deployment
metadata:
  name: verify-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: verify
  template:
    metadata:
      labels:
        app: verify
    spec:
      initContainers:
      - name: init-verify-db
        image: busybox
        command: ['sh', '-c', 'until nslookup verify-db-service; do echo waiting for verify-db to run; sleep 2; done;']
      containers:
      - name: verify
        image: tonyxie2017/unity-verify:latest
        ports:
        - containerPort: 8446
        volumeMounts:
        - name: config-volume
          mountPath: /config
        env:
        - name: SPRING_CONFIG_LOCATION
          value: "/config/application.properties"
        - name: POSTGRES_USERNAME
          valueFrom:
            secretKeyRef:
              name: db-secret
              key: POSTGRES_USERNAME
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: db-secret
              key: POSTGRES_PASSWORD
        - name: JWT_SECRET
          valueFrom:
            secretKeyRef:
              name: jwt-secret
              key: JWT_SECRET
      volumes:
      - name: config-volume
        configMap:
          name: verify-config
          items:
              - key: application.properties
                path: application.properties
---
apiVersion: v1
kind: Service
metadata:
  name: verify-service
  
spec:
  selector:
    app: verify
  ports:
    - protocol: TCP
      port: 8446
      targetPort: 8446