apiVersion: v1
kind: Service
metadata:
  name: verify-db-service
spec:
  ports:
  - port: 5432
    name: verify-db
  clusterIP: None
  selector:
    app: verify-db
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: verify-db
spec:
  selector:
    matchLabels:
      app: verify-db
  serviceName: "verify-db-service"
  replicas: 1
  template:
    metadata:
      labels:
        app: verify-db
    spec:
      containers:
      - name: verify-db
        image: postgres:13
        ports:
        - containerPort: 5432
          name: verify-db
        env:
        - name: POSTGRES_USERNAME
          valueFrom:
            secretKeyRef:
              name: db-secret
              key: POSTGRES_USERNAME
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: db-secret
              key: POSTGRES_PASSWORD
        - name: POSTGRES_DB
          value: cloud
      - name: pgsql-listener
        image: tonyxie2017/pgsql-listener:latest
        env:
          - name: PRIMARY_DB_HOST
            value: verify-db-service
          - name: PRIMARY_DB_PORT
            value: "5432"
          - name: PRIMARY_DB_USER
            valueFrom:
              secretKeyRef:
                name: db-secret
                key: POSTGRES_USERNAME
          - name: PRIMARY_DB_PASSWORD
            valueFrom:
              secretKeyRef:
                name: db-secret
                key: POSTGRES_PASSWORD
          - name: PRIMARY_DB_NAME
            value: "cloud"
          - name: OPERATOR_URL
            value: "http://pgsqlreader-operator-service:8080/sync"
        volumeMounts:
        - name: verify-db-storage
          mountPath: /data
  volumeClaimTemplates:
  - metadata:
      name: verify-db-storage
    spec:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: ebs-sc
      resources:
        requests:
          storage: 1Gi
