apiVersion: apps/v1
kind: Deployment
metadata:
  name: main-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: main
  template:
    metadata:
      labels:
        app: main
    spec:
      containers:
      - name: main
        image: tonyxie2017/unity-main:latest
        ports:
        - containerPort: 8444
        volumeMounts:
        - name: config-volume
          mountPath: /config
        env:
        - name: SPRING_CONFIG_LOCATION
          value: "/config/application.yaml"
        - name: POSTGRES_USER
          valueFrom:
            secretKeyRef:
              name: main-secret
              key: POSTGRES_USER
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: main-secret
              key: POSTGRES_PASSWORD
      volumes:
      - name: config-volume
        configMap:
          name: main-config
          items:
              - key: application.yaml
                path: application.yaml
---
apiVersion: v1
kind: Service
metadata:
  name: main-service  
spec:
  selector:
    app: main
  ports:
    - protocol: TCP
      port: 8444
      targetPort: 8444