apiVersion: v1
kind: Service
metadata:
  name: main-db-service
spec:
  ports:
  - port: 5432
    name: main-db
  clusterIP: None
  selector:
    app: main-db
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: main-db
spec:
  selector:
    matchLabels:
      app: main-db
  serviceName: "main-db-service"
  replicas: 1
  template:
    metadata:
      labels:
        app: main-db
    spec:
      containers:
      - name: main-db
        image: postgres:13
        ports:
        - containerPort: 5432
          name: main-db
        env:
        - name: POSTGRES_DB
          value: main
        - name: POSTGRES_USER
          valueFrom:
            secretKeyRef:
              name: postgres-secrets
              key: POSTGRES_USER
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: postgres-secrets
              key: POSTGRES_PASSWORD
        volumeMounts:
        - name: main-db-storage
          mountPath: /var/lib/postgresql/data
  volumeClaimTemplates:
  - metadata:
      name: main-db-storage
    spec:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: ebs-sc
      resources:
        requests:
          storage: 5Gi
