apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: frontend
        image: tonyxie2017/unity-frontend:latest
        ports:
        - containerPort: 80
        env:
        - name: VUE_APP_API_URL
          valueFrom:
            configMapKeyRef:
              name: frontend-config
              key: VUE_APP_API_URL