apiVersion: v1
kind: Deployment
metadata:
  name: verify-deployment
  namespace: microservices
spec:
  replicas: 3
  selector:
    matchLabels:
      app: verify
  template:
    metadata:
      labels:
        app: verify
    spec:
      containers:
      - name: verify
        image: tonyxie2017/unity-verify:latest
        ports:
        - containerPort: 8446
        volumeMounts:
        - name: config-volume
          mountPath: /config
          subPath: application.properties
        env:
        - name: SPRING_CONFIG_LOCATION
          value: "/config/application.properties"
        - name: PGSQL_USER
          valueFrom:
            secretKeyRef:
              name: pgsql-secret
              key: username
        - name: PGSQL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: pgsql-secret
              key: password
        - name: JWT_SECRET
          valueFrom:
            secretKeyRef:
              name: jwt-secret
              key: jwt-key
      volumes:
      - name: config-volume
        configMap:
          name: verify-config
---
apiVersion: v1
kind: Service
metadata:
  name: verify-service
  namespace: microservices
spec:
  selector:
    app: verify
  ports:
    - protocol: TCP
      port: 8446
      targetPort: 8446