apiVersion: v1
kind: Deployment
metadata:
  name: frontend-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: frontend
        image: # To do
        ports:
        - containerPort: 8080
        env:
        - name: VUE_APP_API_URL
          valueFrom:
            configKeyRef:
              name: frontend-config
              key: VUE_APP_API_URL