spring:
  data:
    redis:
      host: localhost
      port: 6379
      database: 0
  cloud:
    gateway:
      routes:
        - id: auth_service
          uri: http://localhost:8443
          predicates:
            - Path=/auth/**
        - id: login_service
          uri: http://localhost:8444
          predicates:
            - Path=/login/**
        - id: main_service
          uri: http://localhost:8445
          predicates:
            - Path=/main/**
          filters:
            - name: JwtAuthGatewayFilter
  application:
    name: Auth

server:
  port: 8443
jwt:
  secret: p4M/KQlpQ1gP1HcBfLl9t0Sjx5Ff/oeWrtfsdhWld8qS4gn97A0Hg3bYpUNSsdHQD0qH2rDP7AEfPQ2KpGxyXA==
  expiration: 604800
