spring:
  data:
    redis:
      host: localhost
      port: 6379
      database: 0
  cloud:
    gateway:
      routes:
        - id: auth_service
          uri: http://localhost:8443
          predicates:
            - Path=/auth/**
        - id: main_service
          uri: http://localhost:8444
          predicates:
            - Path=/api/main/**
          filters:
            - name: JwtAuth
        - id: profile_service
          uri: http://localhost:8445
          predicates:
            - Path=/api/profile/**
          filters:
            - name: JwtAuth
        - id: verify_service
          uri: http://localhost:8446
          predicates:
            - Path=/api/verify/**
      globalcors:
        cors-configurations:
            '[/**]':
                allowedOrigins: "*"
                allowedMethods:
                - GET
                - POST
                - PUT
                - DELETE
                - PATCH
                allowedHeaders:
                - "*"
                maxAge: 3600
      default-filters:
        - DedupeResponseHeader=Vary Access-Control-Allow-Origin , RETAIN_FIRST
  application:
    name: Auth
  main:
    web-application-type: reactive
  zipkin:
    base-url: http://localhost:9411
  sleuth:
    sampler:
      probability: 1.0

server:
  port: 8443
jwt:
  secret: p4M/KQlpQ1gP1HcBfLl9t0Sjx5Ff/oeWrtfsdhWld8qS4gn97A0Hg3bYpUNSsdHQD0qH2rDP7AEfPQ2KpGxyXA==
  expiration: 604800


management:
  tracing:
    sampling:
      probability: 1.0

