spring:
  data:
    redis:
      host: localhost
      port: 6379
      database: 0
  cloud:
    gateway:
      routes:
        - id: auth_service
          uri: http://localhost:8443
          predicates:
            - Path=/auth/**
        - id: main_service
          uri: http://localhost:8444
          predicates:
            - Path=/api/main/**
          filters:
            - name: JwtAuthGatewayFilter
        - id: profile_service
          uri: http://localhost:8445
          predicates:
            - Path=/profile/**
          filters:
            - name: JwtAuthGatewayFilter
        - id: verify_service
          uri: http://localhost:8446
          predicates:
            - Path=/api/verify/**
  application:
    name: Auth

server:
  port: 8443
jwt:
  secret: p4M/KQlpQ1gP1HcBfLl9t0Sjx5Ff/oeWrtfsdhWld8qS4gn97A0Hg3bYpUNSsdHQD0qH2rDP7AEfPQ2KpGxyXA==
  expiration: 604800
