apiVersion: v1
kind: ConfigMap
metadata:
  name: auth-config
  
data:
  application.yaml: |
    spring:
      data:
        redis:
          host: redis-service
          port: 6379
          database: 0
      cloud:
        gateway:
          routes:
            - id: main_service
              uri: http://main-service:8444
              predicates:
                - Path=/api/main/**
              filters:
                - name: JwtAuth
            - id: user_service
              uri: http://user-service:8445
              predicates:
                - Path=/api/profile/**
              filters:
                - name: JwtAuth
            - id: verify_service
              uri: http://verify-service:8446
              predicates:
                - Path=/api/verify/**
          globalcors:
            cors-configurations:
                '[/**]':
                    allowedOrigins: "*"
                    allowedMethods:
                    - GET
                    - POST
                    - PUT
                    - DELETE
                    - PATCH
                    allowedHeaders:
                    - "*"
                    maxAge: 3600
          default-filters:
            - DedupeResponseHeader=Vary Access-Control-Allow-Origin , RETAIN_FIRST
      application:
        name: Auth
      main:
        web-application-type: reactive
    server:
      port: 8443
    jwt:
      secret: ${JWT_SECRET}
      expiration: 604800000