apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: pgsqlreaders.example.com
spec:
  group: example.com
  versions:
    - name: v1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                secondary:
                  type: array
                  items:
                    type: object
                    properties:
                      url:
                        type: string
                      username:
                        type: string
                      password:
                        type: string
  scope: Namespaced
  names:
    plural: pgsqlreaders
    singular: pgsqlreader
    kind: PgsqlReader
    shortNames:
      - pgsqlr
