apiVersion: v1
kind: Deployment
metadata:
  name: main-deployment
  namespace: microservices
spec:
  replicas: 3
  selector:
    matchLabels:
      app: main
  template:
    metadata:
      labels:
        app: main
    spec:
      containers:
      - name: main
        image: tonyxie2017/unity-main:latest
        ports:
        - containerPort: 8444
        volumeMounts:
        - name: config-volume
          mountPath: /config
          subPath: application.properties
        env:
        - name: SPRING_CONFIG_LOCATION
          value: "/config/application.properties"
        - name: PGSQL_USER
          valueFrom:
            secretKeyRef:
              name: pgsql-secret
              key: username
        - name: PGSQL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: pgsql-secret
              key: password
      volumes:
      - name: config-volume
        configMap:
          name: main-config
---
apiVersion: v1
kind: Service
metadata:
  name: main-service
  namespace: microservices
spec:
  selector:
    app: main
  ports:
    - protocol: TCP
      port: 8444
      targetPort: 8444